### ISSUE TITLE
Da fixare importante 

### ISSUE THREAD

**Issue by AngelaDeM** [marcociano/MAG_News_Verification#4]
![immagine issue](https://user-images.githubusercontent.com/81226666/219944651-ef9f3e73-bb4d-4d1f-b0ce-52f7296a40b5.png)

Inserendo staticamente dei dati per testare il funzionamento del Line Chart (secondo il criterio che la prima linea indica la percentuale di fake news e la seconda assume i valori 0-50 per indicare fake oppure no) accade quanto si vede in figura anche se non compaiono errori.

**Comment by marcociano** [comment]
Risolto il problema riguardante la gestione dinamica della singola "line" appartenente al line chart con successiva risoluzione del problema delle Lable multiple sull'asse delle ascisse.
